(define whattriangle?
  (lambda (a b c)
    (if (or (> (+ a b) c)
            (> (+ a c) b)
            (> (+ b c) a))
        (cond ((or (= (+ (* a a) (* b b)) (* c c))
                   (= (+ (* b b) (* c c)) (* a a))
                   (= (+ (* c c) (* a a)) (* b b)))
                   (if (or (= a b) (= b c) (= c a)) "Right Isosceles" "Right")
              ((= a b c) "Equilateral"))
              ((and 
                (or (= (+ (* a a) (* b b)) (* c c))
                    (= (+ (* b b) (* c c)) (* a a))
                    (= (+ (* c c) (* a a)) (* b b)))
                (or (= a b) (= b c) (= c a))) "Right Isosceles")
              ((or (= a b) (= b c) (= c a)) "Isosceles")
              ((or (= (+ (* a a) (* b b)) (* c c))
                   (= (+ (* b b) (* c c)) (* a a))
                   (= (+ (* c c) (* a a)) (* b b))) "Right")
              (else "Scalene"))
        "Not A Triangle")))